### ISSUE TITLE
TopicPage.getArticles returns the articles in an array instead of the raw return value

### ISSUE THREAD

**Issue by joelhulen** [EventRegistry/event-registry-node-js#16]
I have compared this behavior to the Python SDK: https://github.com/EventRegistry/event-registry-python/blob/89493418bbe3a0a6b6ebe957ec03f5a63fb2db70/eventregistry/TopicPage.py#L376

The Python SDK returns the raw result from `/api/v1/article/api/v1/article` which, among other things, provides the `pages` value. One can easily retrieve the `articles.results` array property on their own and still be able to implement paging from the client.

However, in the NodeJS version of the SDK, this method returns `data.articles.results`, which prevents the client from implementing paging since the `pages` property is excluded: https://github.com/EventRegistry/event-registry-node-js/blob/87ef9ec3fce55abde78364b50737d497239815e9/src/topicPage.ts#L448

Could you please update this behavior, add a new function, or provide a simple workaround?

**Comment by UnspokenMallard** [comment]
Hi, I'll update this function's behaviour so that it's in line with the Python SDK counterpart. Update will be issued shortly.

**Comment by UnspokenMallard** [comment]
Update is live (version 8.10.1), `getArticles` and `getEvents` now return full responses, similar to the Python SDK.

**Comment by joelhulen** [comment]
Thank you for the quick resolution!
