### ISSUE TITLE
How can we disable the creation of the logs directory to make it usable in a serverless environment.

### ISSUE THREAD

**Issue by CreativeTransmissions** [EventRegistry/event-registry-node-js#19]
Hi there,

I'm considering using this package and API for a new project an have an article query running locally.

When deploying to a serverless environment where there is no directory structure, my app errors out as it appears that the logger always tries to create a logs directory on instantiation of erBase.

Setting logging to false makes no difference:

```
    const er = new erBase.EventRegistry({
        apiKey: NEWS_API_KEY,
        allowUseOfArchive: false,
        logging: false
    });
``` 

Is there any way to cancel log directory creation?

**Comment by UnspokenMallard** [comment]
I apologize for the late response. The recent release (version 9.1.1) fixed how the logging parameter is treated. When passing logging as false, no `logs` folder should be created. If you have any more issues or questions do let me know.
