### ISSUE TITLE
Source image uris not linking to images

### ISSUE THREAD

**Issue by michellelockett** [EventRegistry/event-registry-node-js#6]
The image urls and thumbnail urls that are returning for sources are linking to a 404 page not found.  
e.g. for New York Times
http://pbs.twimg.com/profile_images/758384037589348352/KB3RFwFm_bigger.jpg

No webpage was found for the web address: https://pbs.twimg.com/profile_images/758384037589348352/KB3RFwFm_bigger.jpg
HTTP ERROR 404

Is there something additional I need to do on my end to interact with or retrieve the twitter images?

**Comment by UnspokenMallard** [comment]
Hi,

some twitter image links are prone to change over time thus becoming obsolete or broken. 
We are working on updating all obsolete (twitter) image links.

Best regards,
Anze
